### ISSUE TITLE
import doesn't work

### ISSUE THREAD

**Issue by nickyharpor** [redstone-finance/redstone-smartcontracts#110]
I just did `import * as SmartWeaveSdk from 'redstone-smartweave'` as in the docs and I get this error:

```
...\node_modules\redstone-isomorphic\npm-node.js:14
        global.Response = realFetch.Response;
                                    ^

TypeError: Cannot read property 'Response' of undefined
```

**Comment by ppedziwiatr** [comment]
Hey @nickyharpor can you please share some more details? which node.js version are you using, sdk version, etc? or maybe simply please share your project.

We have a separate repo with examples - https://github.com/redstone-finance/redstone-smartcontracts-examples - can you please verify if examples from this repo work for you?

**Comment by nickyharpor** [comment]
my bad! I installed the latest nodejs and the problem is gone.
