### ISSUE TITLE
Feature Request: Browser Bundle

### ISSUE THREAD

**Issue by nickyharpor** [redstone-finance/redstone-smartcontracts#115]
One of the ways to make an Arweave app fully decentralized is to run it all on client machine (i.e. no backend). To connect to Arweave network and smart contracts directly from the browser, I need a browser js bundle.

**Comment by ppedziwiatr** [comment]
In the meantime - web bundlers can be used.
Example react app for webpack4 - https://github.com/redstone-finance/redstone-smartcontracts-app
webpack5 - https://github.com/redstone-finance/redstone-smartcontracts-webpack5-app

**Comment by asiaziola** [comment]
@nickyharpor New version v0.4.41 has been released. We added bundles for browser environment. You can check following readme section to see how you can use it in your webiste :) https://github.com/redstone-finance/redstone-smartcontracts#using-web-bundles
