### ISSUE TITLE
feat: add an option to deploy contracts through bundles

### ISSUE THREAD

**Issue by wkolod** [redstone-finance/redstone-smartcontracts#127]
Currently, when the `internalWrites` flag is set to `true` in the contract `EvaluationOptions`, the following error is received while deploying a new contract and writing an interaction immediately afterwards: `Unable to retrieve tx <txId>. undefined. undefined`.
This could be solved by using RedStone gateway and sequencer to deploy contracts, as it is currently done for contract interactions.
Proposition: add an option for bundled contract creation for these two functions:
- `smartweave.createContract.deployFromSourceTx()`
- `smartweave.createContract.deploy()`

**Comment by ppedziwiatr** [comment]
deployed on prod, required SDK min. `0.4.69`
