### ISSUE TITLE
__filename breaks in Web

### ISSUE THREAD

**Issue by DougAnderson444** [redstone-finance/redstone-smartcontracts#34]
https://github.com/redstone-finance/redstone-smartcontracts/blob/8b61a4b6897056ce2eb1fc77c6600b14a9f83853/src/core/modules/impl/DefaultCreateContract.ts#L5

Trying to bundle this line using Vite breaks, since `__filename` i a nodejs feature, it breaks in the browser.

**Comment by ppedziwiatr** [comment]
Hi @DougAnderson444 , thanks for posting this issue. It should be now fixed in the `0.3.10-alpha.13` version.
