### ISSUE TITLE
[Proposal] Plugins

### ISSUE THREAD

**Issue by andreespirela** [redstone-finance/redstone-smartcontracts#48]
Hello Redstone, this is Andres from Verto.exchange.

**Overview**:
Plugins are a way to introduced custom Javascript functions to the execution of smart weave contracts.

**Details**:
Plugins should be passed in a static call to a setter, for example:
```typescript
import { setPlugins } from "smartweave";

setPlugins({
   helloWorld: () => console.log("hello world");
});
````
Or they can be passed in the `readContract` function.

```typescript
export declare function readContract(arweave: Arweave, contractId: string, height?: number, returnValidity?: boolean, plugins?: any): Promise<any>
```

```typescript
import { readContract } from "smartweave";

readContract(arweaveClient,
            contractId,
            undefined,
            true,
            {
                helloWorld: () => console.log("hello world");
            }
);
```

**Accessing plugins**
In order to access the plugins _inside_ the contract, we can do:
```typescript
SmartWeave.plugins[plugin_name]();
```
where SmartWeave is the global that all contract has, with a new object, which is call `plugins`, and contains the functions we passed in our object

```typescript
SmartWeave.plugins['helloWorld']();
```

**Security Flaws**
A contract can override, or modify the `plugins` object. For this reason, this object should be frozen, and all its properties should also be frozen. A deep `Object.freeze` if you may.

cc @t8

**Comment by ppedziwiatr** [comment]
Hey.

Can you please explain what is the potential use case?
I'm afraid that using non-standard (maybe even non-public?) plug-ins (that somehow extend the base protocol) could potentially break the contract state evaluation on endpoints, that are un-aware of such add-ons.

**Comment by andreespirela** [comment]
> Hey.
> 
> Can you please explain what is the potential use case? I'm afraid that using non-standard (maybe even non-public?) plug-ins (that somehow extend the base protocol) could potentially break the contract state evaluation on endpoints, that are un-aware of such add-ons.

We have a cache API and the idea is to be able to pass some of these functions to do some verifications to the contract. In the future, it might also be useful to create our own execution functions or utilities that users can use inside Verto.

**Comment by ppedziwiatr** [comment]
> > Hey.
> > Can you please explain what is the potential use case? I'm afraid that using non-standard (maybe even non-public?) plug-ins (that somehow extend the base protocol) could potentially break the contract state evaluation on endpoints, that are un-aware of such add-ons.
> 
> We have a cache API and the idea is to be able to pass some of these functions to do some verifications to the contract. In the future, it might also be useful to create our own execution functions or utilities that users can use inside Verto.

I see, we will discuss this internally and will let you know soon.

**Comment by ppedziwiatr** [comment]
@andreespirela , as we're really having some doubts re. this feature (as mentioned previously - using some custom plugins will basically ruin the option to properly evaluate the state by any of the network participants) - one last proposal - have you considered extracting your caching API to a separate class and (with the help of a proper build process) - merge it with the contract's code?

An example of such feature is available here:
https://github.com/redstone-finance/redstone-smartweave-contracts/blob/main/src/common/ContractAdmin.ts
or here
https://github.com/redstone-finance/redstone-smartweave-contracts/blob/main/src/common/ContractInteractions.ts

- these classes are then bundled into the resulting contract's source code (using esbuild's iife bundle format) and used within contracts like this:
https://github.com/redstone-finance/redstone-smartweave-contracts/blob/main/src/token/token.contract.ts#L139

or:
https://github.com/redstone-finance/redstone-smartweave-contracts/blob/main/src/providers-registry/providers-registry.contract.ts#L45
