### ISSUE TITLE
fileCacheBase issue

### ISSUE THREAD

**Issue by zyjblockchain** [redstone-finance/redstone-smartcontracts#55]
I use filecache ways to sync smc, 
and I remove MemBlockHeightSwCache 
and get this error
it is normally?
![image](https://user-images.githubusercontent.com/40423181/144200142-b3e708b5-a398-4650-a8f2-1915a6db8502.png)

**Comment by ppedziwiatr** [comment]
fixed in `0.4.1`.
Please read description from https://github.com/redstone-finance/redstone-smartcontracts/pull/56
and https://github.com/redstone-finance/redstone-smartcontracts/pull/57 - as both the format and behaviour of file cache have changed.
