### ISSUE TITLE
tests: regression tests performance

### ISSUE THREAD

**Issue by ppedziwiatr** [redstone-finance/redstone-smartcontracts#73]
Regression tests are super important, because they give us a high degree of confidence, that the state evaluated by the SDK is proper...BUT the current performance is killing me. On my M1, regression of all the ~110 verified contracts runs for about 12m, on GH actions it takes about 30m?

The main issue here are the calls to Arweave GQL endpoint (or rather slow response times).

Now, I wonder if maybe we should migrate these tests to our RedStone Gateway - this would speed them up significantly and would still test the SDK implementation. RedStone Gateway has its own set of regression tests, so this shouldn't affect the overall testing "quality".

@asiaziola , what do you think?

**Comment by asiaziola** [comment]
Sounds reasonable, although i'm not fully convinced we should omit Arweave gateway entirely when testing SDK implementation as SDK's gonna be used both - Redstone and Arweave ways. 

Of course in RedStone Gateway we trust but maybe we could migrate most of the tests to our gateway and leave any Arweave tests just for sanity check. At the end of the day - these performance issues you've mentioned are sth we - as devs - need to put up with and not the end users, so I guess it's not sth critical :)

Anyway, additionally, regression tests should be probably better described when it comes to its titles and variables (result1, result2...).

**Comment by ppedziwiatr** [comment]
Just realized that it won't be possible to "inject" the redstone gateway into the smartweave.js...we would need to make it GQL compatible, and I'm somewhat afraid that GQL could kill the performance here

**Comment by ppedziwiatr** [comment]
ok, leaving as is for now..
