### ISSUE TITLE
perf: possible mem leak in v8.serialize()

### ISSUE THREAD

**Issue by ppedziwiatr** [redstone-finance/redstone-smartcontracts#86]
Issue raised by Pianity.
In some environments the rss memory usage grows to very large values (it does not happen on my M1 though).
This is probably related to https://github.com/nodejs/node/issues/40828

Removing the v8's serialization (https://github.com/redstone-finance/redstone-smartcontracts/pull/84/files#diff-5acab41990585fa68ae01ff7b2e2915628d19237840c3061b31fcadc1c0f09b8) fixed the memory leak issues, but at a cost of performance - therefore a better solution needs to be developed.

**Comment by ppedziwiatr** [comment]
switch to https://developer.mozilla.org/en-US/docs/Web/API/structuredClone when it will be implemented by most of the browsers.

**Comment by balthazar** [comment]
👍🏻 Subscribing

**Comment by ppedziwiatr** [comment]
Performance comparison ("state evaluation" column) for "loot" contract:

1. `@ungap/structured-clone`
<img width="945" alt="image" src="https://user-images.githubusercontent.com/84311757/156888143-1c540e24-c0a9-40fe-ad10-1c26c6f19cb5.png">

2. `v8.deserialize(v8.serialize(input))`
<img width="945" alt="image" src="https://user-images.githubusercontent.com/84311757/156888201-6c935564-347e-44c7-8eab-9cd53c8a0f31.png">

3. `lodash/cloneDeep`
<img width="945" alt="image" src="https://user-images.githubusercontent.com/84311757/156888467-5569f5f6-5331-4708-8264-d17c50198643.png">

**Comment by balthazar** [comment]
Maybe I'm not reading the bench correctly, but isn't lodash more performant than ungap here?

**Comment by ppedziwiatr** [comment]
> Maybe I'm not reading the bench correctly, but isn't lodash more performant than ungap here?

You're reading the bench correctly ;-) lodash indeed is more performant than ungap and v8. Though I believe that for "bigger" states - v8 was the winner. Anyway, I'll stick with lodash for now...

**Comment by ppedziwiatr** [comment]
Just a word of comment if anyone was interested - deepCopy-ing of the state is required for each interaction - before the state is passed to the contract's handler function. Contracts usually modify the state directly and without deepCopy - there would be risk of changing values somewhere in the host code (eg. values stored in cache).

v1 performed here simple stringify/parse https://github.com/ArweaveTeam/SmartWeave/blame/master/src/contract-step.ts#L56 - which obv. is least performant.

This won't be an issue in case of WASM contract - which store their state in the wasm module memory.

**Comment by ppedziwiatr** [comment]
fixed in https://github.com/redstone-finance/redstone-smartcontracts/pull/108, released in `0.4.36`

**Comment by balthazar** [comment]
Ah ok, I was confused with the commits being referenced using ungap, but they were probably old

🎉 Will try this
