### ISSUE TITLE
sdk cannot load transaction from Arweave gateway..

### ISSUE THREAD

**Issue by vinciis2018** [redstone-finance/redstone-smartcontracts#96]
getting this message in my cli while interacting with smartweave. [This makes](https://github.com/redstone-finance/redstone-smartcontracts/blob/main/src/utils/ArweaveWrapper.ts#L83). This is creating issue in case a frontend page trying to fetch data from a backend reading a contract, which is giving timeout error. And this error comes randomly. While the page shows code 503, the sdk keeps on functioning in the backend cli.
![Screenshot (76)](https://user-images.githubusercontent.com/57892090/154654657-ee9ef925-14dc-4bce-97f9-9e0d11fa819d.png)

**Comment by ppedziwiatr** [comment]
duplicates https://github.com/redstone-finance/redstone-smartcontracts/issues/97
